version: "3"
services:
  image-annotation-tool:
    build: .
    ports:
      - "3001:3000"
    restart: unless-stopped
  mongodb:
    image: mongo:4.4.1
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
