version: "3"
services:
  image-annotation-tool:
    image: image-annotation-tool:latest
    ports:
      - "3001:3000"
    restart: unless-stopped
  image-annotation-tool-worker:
    image: image-annotation-tool:latest
    command: npm run start:worker
    restart: unless-stopped
  mongodb:
    image: mongo:4.4.1
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
  rabbitmq:
    image: rabbitmq:3.8.9-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
